"""create chats table

Revision ID: 00db31c1ba37
Revises: 5bcf5f672977
Create Date: 2025-10-04 23:35:48.500285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00db31c1ba37'
down_revision = '5bcf5f672977'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
