"""create lostandfound table

Revision ID: 02df0b7c0504
Revises: 31133cc8d080
Create Date: 2025-09-22 15:51:32.020498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02df0b7c0504'
down_revision = '31133cc8d080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lostandfound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('isResolved', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lostandfound_id'), 'lostandfound', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lostandfound_id'), table_name='lostandfound')
    op.drop_table('lostandfound')
    # ### end Alembic commands ###
