"""create chats table

Revision ID: 2826eb14d4e2
Revises: c59beef29072
Create Date: 2025-10-03 09:54:21.376907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2826eb14d4e2'
down_revision = 'c59beef29072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
