"""add messages table

Revision ID: 31133cc8d080
Revises: 5c30fc5652db
Create Date: 2025-09-22 15:21:20.546389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31133cc8d080'
down_revision = '5c30fc5652db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('name', sa.Text(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('group', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('userType', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('userImg', sa.Text(), nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.TEXT(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.TEXT(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.TEXT(), nullable=False))
    op.drop_column('users', 'userImg')
    op.drop_column('users', 'userType')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'group')
    op.drop_column('users', 'name')
    op.drop_column('users', 'password')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
