"""create chats table

Revision ID: 457a1411105c
Revises: eeeeeeeeeeee
Create Date: 2025-10-03 09:04:30.299371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457a1411105c'
down_revision = 'eeeeeeeeeeee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lostandfound', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('uq_lostandfound_item_id'))
        batch_op.create_unique_constraint('uq_lostandfound_item_id', ['item_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_uuid',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index(batch_op.f('uq_users_user_uuid'))
        batch_op.create_unique_constraint('uq_users_user_uuid', ['user_uuid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_user_uuid', type_='unique')
        batch_op.create_index(batch_op.f('uq_users_user_uuid'), ['user_uuid'], unique=1)
        batch_op.alter_column('user_uuid',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('lostandfound', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lostandfound_item_id', type_='unique')
        batch_op.create_index(batch_op.f('uq_lostandfound_item_id'), ['item_id'], unique=1)
        batch_op.alter_column('userId',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
