"""create chats table

Revision ID: 532d4f6be95b
Revises: 00db31c1ba37
Create Date: 2025-10-05 13:13:20.670362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532d4f6be95b'
down_revision = '00db31c1ba37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
