"""create chats table

Revision ID: 5bcf5f672977
Revises: 2826eb14d4e2
Create Date: 2025-10-03 09:57:32.064410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcf5f672977'
down_revision = '2826eb14d4e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
