"""replace type with isLost in lostandfound

Revision ID: a237a0890b62
Revises: d9b588eda6fa
Create Date: 2025-09-22 16:01:20.064239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a237a0890b62'
down_revision = 'd9b588eda6fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
