"""create chats table

Revision ID: c59beef29072
Revises: 457a1411105c
Create Date: 2025-10-03 09:53:07.465388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59beef29072'
down_revision = '457a1411105c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lostandfound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lostandfound', schema=None) as batch_op:
        batch_op.drop_column('userName')

    # ### end Alembic commands ###
