"""create chats table

Revision ID: c8fb3fdaeec5
Revises: cf20f27c9e38
Create Date: 2025-09-29 12:43:05.815336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fb3fdaeec5'
down_revision = 'cf20f27c9e38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add columns only if they don't already exist (SQLite-safe)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = {col['name'] for col in inspector.get_columns('chats')}

    if 'user_names' not in existing:
        op.add_column('chats', sa.Column('user_names', sa.Text(), nullable=False, server_default=''))
    if 'last_message' not in existing:
        op.add_column('chats', sa.Column('last_message', sa.Text(), nullable=True))
    if 'item' not in existing:
        op.add_column('chats', sa.Column('item', sa.Text(), nullable=True))
    if 'item_image' not in existing:
        op.add_column('chats', sa.Column('item_image', sa.Text(), nullable=True))
    if 'item_id' not in existing:
        op.add_column('chats', sa.Column('item_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'item_id')
    op.drop_column('chats', 'item_image')
    op.drop_column('chats', 'item')
    op.drop_column('chats', 'last_message')
    op.drop_column('chats', 'user_names')
    # ### end Alembic commands ###
