"""create chats table

Revision ID: c8fb3fdaeec5
Revises: cf20f27c9e38
Create Date: 2025-09-29 12:43:05.815336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fb3fdaeec5'
down_revision = 'cf20f27c9e38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
