"""replace type with isLost in lostandfound

Revision ID: d9b588eda6fa
Revises: eda87fd6e6bd
Create Date: 2025-09-22 16:00:36.821783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b588eda6fa'
down_revision = 'eda87fd6e6bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lostandfound', sa.Column('isLost', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.drop_column('lostandfound', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lostandfound', sa.Column('type', sa.TEXT(), nullable=False))
    op.drop_column('lostandfound', 'isLost')
    # ### end Alembic commands ###
