"""create lostandfound table

Revision ID: eda87fd6e6bd
Revises: 02df0b7c0504
Create Date: 2025-09-22 15:53:31.398624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda87fd6e6bd'
down_revision = '02df0b7c0504'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
